[package]
name = "canonic"
version = "0.2.0"
edition = "2024"
license = "MIT"
description = "a library for structured paths"

[features]
default = ["std"]
alloc = []
std = ["alloc", "dirs"]

[dependencies]
dirs = { version = "6.0.0", optional = true }

[dev-dependencies]
rstest = "0.25.0"
